name: Codecov workflow

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Generate coverage report
        run: |
          npm ci
          npm test -- --coverage
        env:
          CI: true
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: coverage/coverage-final.json
          flags: unittests
          name: codecov-umbrella
