name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@master
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - run: npm ci
    - run: npm test
      env:
        CI: true
    - run: npm run build --if-present
    - name: Deploy
      env:
        TEST: AMAZING_IT_WORKS!
      run: node ./.github/scripts/deploy.js