name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: 10.x

      - run: npm ci
        env:
          SUPPRESS_SUPPORT: true
      - run: |
          npm test
          npm test --coverage
        env:
          CI: true
      - run: npm run build --if-present
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
