name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - uses: actions/checkout@master
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: 10.x
      - run: |
          npm ci
          npm test
          npm run build --if-present
        env:
          SUPPRESS_SUPPORT: true
          CI: true
